name: Deploy JupyterLite
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlite/actions/build@v1
      - uses: jupyterlite/actions/deploy@v1
        with:
          branch: gh-pages
          target: .
